name: My First Workflow

on:
  push:
    braches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello , Github Actions"
